//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 03:01:05 PM CET 
//


package it.titulus.docpublished;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}classif"/>
 *         &lt;element ref="{}mittente" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="scarto" default="99">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="01"/>
 *             &lt;enumeration value="05"/>
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="99"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "classif",
    "mittente"
})
@XmlRootElement(name = "minuta")
public class Minuta {

    @XmlElement(required = true)
    protected Classif classif;
    protected Mittente mittente;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String scarto;

    /**
     * Gets the value of the classif property.
     * 
     * @return
     *     possible object is
     *     {@link Classif }
     *     
     */
    public Classif getClassif() {
        return classif;
    }

    /**
     * Sets the value of the classif property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classif }
     *     
     */
    public void setClassif(Classif value) {
        this.classif = value;
    }

    /**
     * Gets the value of the mittente property.
     * 
     * @return
     *     possible object is
     *     {@link Mittente }
     *     
     */
    public Mittente getMittente() {
        return mittente;
    }

    /**
     * Sets the value of the mittente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mittente }
     *     
     */
    public void setMittente(Mittente value) {
        this.mittente = value;
    }

    /**
     * Gets the value of the scarto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScarto() {
        if (scarto == null) {
            return "99";
        } else {
            return scarto;
        }
    }

    /**
     * Sets the value of the scarto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScarto(String value) {
        this.scarto = value;
    }

}
