//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.29 at 03:01:05 PM CET 
//


package it.titulus.docpublished;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="diritto" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="RPA"/>
 *             &lt;enumeration value="RPAM"/>
 *             &lt;enumeration value="CC"/>
 *             &lt;enumeration value="CDS"/>
 *             &lt;enumeration value="CDSM"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nome_persona" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nome_uff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cod_persona" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cod_uff" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipo_uff" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="scartato">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="true"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="intervento">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="si"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "rif_interno")
public class RifInterno {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String diritto;
    @XmlAttribute(name = "nome_persona", required = true)
    protected String nomePersona;
    @XmlAttribute(name = "nome_uff", required = true)
    protected String nomeUff;
    @XmlAttribute(name = "cod_persona")
    protected String codPersona;
    @XmlAttribute(name = "cod_uff")
    protected String codUff;
    @XmlAttribute(name = "tipo_uff")
    protected String tipoUff;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String scartato;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String intervento;

    /**
     * Gets the value of the diritto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiritto() {
        return diritto;
    }

    /**
     * Sets the value of the diritto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiritto(String value) {
        this.diritto = value;
    }

    /**
     * Gets the value of the nomePersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomePersona() {
        return nomePersona;
    }

    /**
     * Sets the value of the nomePersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomePersona(String value) {
        this.nomePersona = value;
    }

    /**
     * Gets the value of the nomeUff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeUff() {
        return nomeUff;
    }

    /**
     * Sets the value of the nomeUff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeUff(String value) {
        this.nomeUff = value;
    }

    /**
     * Gets the value of the codPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodPersona() {
        return codPersona;
    }

    /**
     * Sets the value of the codPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodPersona(String value) {
        this.codPersona = value;
    }

    /**
     * Gets the value of the codUff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodUff() {
        return codUff;
    }

    /**
     * Sets the value of the codUff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodUff(String value) {
        this.codUff = value;
    }

    /**
     * Gets the value of the tipoUff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoUff() {
        return tipoUff;
    }

    /**
     * Sets the value of the tipoUff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoUff(String value) {
        this.tipoUff = value;
    }

    /**
     * Gets the value of the scartato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScartato() {
        return scartato;
    }

    /**
     * Sets the value of the scartato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScartato(String value) {
        this.scartato = value;
    }

    /**
     * Gets the value of the intervento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntervento() {
        return intervento;
    }

    /**
     * Sets the value of the intervento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntervento(String value) {
        this.intervento = value;
    }

}
