
package it.archiflow93.email;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2019-06-03T16:40:44.477+02:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "ValidLogCreatedFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class IEMailServiceContractStoreEmailValidLogCreatedFaultFaultFaultMessage extends Exception {
    
    private it.archiflow93.email.ValidLogCreatedFault validLogCreatedFault;

    public IEMailServiceContractStoreEmailValidLogCreatedFaultFaultFaultMessage() {
        super();
    }
    
    public IEMailServiceContractStoreEmailValidLogCreatedFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEMailServiceContractStoreEmailValidLogCreatedFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEMailServiceContractStoreEmailValidLogCreatedFaultFaultFaultMessage(String message, it.archiflow93.email.ValidLogCreatedFault validLogCreatedFault) {
        super(message);
        this.validLogCreatedFault = validLogCreatedFault;
    }

    public IEMailServiceContractStoreEmailValidLogCreatedFaultFaultFaultMessage(String message, it.archiflow93.email.ValidLogCreatedFault validLogCreatedFault, Throwable cause) {
        super(message, cause);
        this.validLogCreatedFault = validLogCreatedFault;
    }

    public it.archiflow93.email.ValidLogCreatedFault getFaultInfo() {
        return this.validLogCreatedFault;
    }
}
