
package it.archiflow93.email;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2019-06-03T16:40:44.447+02:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "NoDataFoundFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class IEMailServiceContractSendExtendedMailNoDataFoundFaultFaultFaultMessage extends Exception {
    
    private it.archiflow93.email.NoDataFoundFault noDataFoundFault;

    public IEMailServiceContractSendExtendedMailNoDataFoundFaultFaultFaultMessage() {
        super();
    }
    
    public IEMailServiceContractSendExtendedMailNoDataFoundFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEMailServiceContractSendExtendedMailNoDataFoundFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEMailServiceContractSendExtendedMailNoDataFoundFaultFaultFaultMessage(String message, it.archiflow93.email.NoDataFoundFault noDataFoundFault) {
        super(message);
        this.noDataFoundFault = noDataFoundFault;
    }

    public IEMailServiceContractSendExtendedMailNoDataFoundFaultFaultFaultMessage(String message, it.archiflow93.email.NoDataFoundFault noDataFoundFault, Throwable cause) {
        super(message, cause);
        this.noDataFoundFault = noDataFoundFault;
    }

    public it.archiflow93.email.NoDataFoundFault getFaultInfo() {
        return this.noDataFoundFault;
    }
}
