
package it.archiflow93.classification;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2019-02-01T10:12:07.677+01:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PreservationClassificationNotEnabledFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class IClassificationServiceGetFascicoloToPreserveByParamPreservationClassificationNotEnabledFaultFaultFaultMessage extends Exception {
    
    private it.archiflow93.classification.PreservationClassificationNotEnabledFault preservationClassificationNotEnabledFault;

    public IClassificationServiceGetFascicoloToPreserveByParamPreservationClassificationNotEnabledFaultFaultFaultMessage() {
        super();
    }
    
    public IClassificationServiceGetFascicoloToPreserveByParamPreservationClassificationNotEnabledFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IClassificationServiceGetFascicoloToPreserveByParamPreservationClassificationNotEnabledFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IClassificationServiceGetFascicoloToPreserveByParamPreservationClassificationNotEnabledFaultFaultFaultMessage(String message, it.archiflow93.classification.PreservationClassificationNotEnabledFault preservationClassificationNotEnabledFault) {
        super(message);
        this.preservationClassificationNotEnabledFault = preservationClassificationNotEnabledFault;
    }

    public IClassificationServiceGetFascicoloToPreserveByParamPreservationClassificationNotEnabledFaultFaultFaultMessage(String message, it.archiflow93.classification.PreservationClassificationNotEnabledFault preservationClassificationNotEnabledFault, Throwable cause) {
        super(message, cause);
        this.preservationClassificationNotEnabledFault = preservationClassificationNotEnabledFault;
    }

    public it.archiflow93.classification.PreservationClassificationNotEnabledFault getFaultInfo() {
        return this.preservationClassificationNotEnabledFault;
    }
}
