package it.kdm.docer.fascicolazione;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2021-07-15T14:46:49.062+02:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://fascicolazione.docer.kdm.it", name = "WSFascicolazionePortType")
@XmlSeeAlso({it.kdm.docer.sdk.classes.xsd.ObjectFactory.class, ObjectFactory.class, it.kdm.docer.fascicolazione.xsd.ObjectFactory.class})
public interface WSFascicolazionePortType {

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:updateFascicolo", output = "urn:updateFascicoloResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:updateFascicoloWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "updateFascicolo", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.UpdateFascicolo")
    @WebMethod(action = "urn:updateFascicolo")
    @ResponseWrapper(localName = "updateFascicoloResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.UpdateFascicoloResponse")
    public java.lang.String updateFascicolo(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "fascicoloid", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> fascicoloid,
        @WebParam(name = "metadati", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> metadati
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:writeConfig", output = "urn:writeConfigResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:writeConfigWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "writeConfig", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.WriteConfig")
    @WebMethod(action = "urn:writeConfig")
    @ResponseWrapper(localName = "writeConfigResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.WriteConfigResponse")
    public java.lang.Boolean writeConfig(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "xmlConfig", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String xmlConfig
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:changeFascicoliById", output = "urn:changeFascicoliByIdResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:changeFascicoliByIdWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "changeFascicoliById", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ChangeFascicoliById")
    @WebMethod(action = "urn:changeFascicoliById")
    @ResponseWrapper(localName = "changeFascicoliByIdResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ChangeFascicoliByIdResponse")
    public java.lang.Boolean changeFascicoliById(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "docNum", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.Long docNum,
        @WebParam(name = "fascicoliToRemove", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.fascicolazione.ArrayOfKeyValuePair> fascicoliToRemove,
        @WebParam(name = "fascicoliToAdd", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.fascicolazione.ArrayOfKeyValuePair> fascicoliToAdd
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:creaFascicolo", output = "urn:creaFascicoloResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:creaFascicoloWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "creaFascicolo", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.CreaFascicolo")
    @WebMethod(action = "urn:creaFascicolo")
    @ResponseWrapper(localName = "creaFascicoloResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.CreaFascicoloResponse")
    public java.lang.String creaFascicolo(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "metadati", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> metadati
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:login", output = "urn:loginResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:loginWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "login", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.Login")
    @WebMethod(action = "urn:login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "userId", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String password,
        @WebParam(name = "codiceEnte", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String codiceEnte
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:updateACLFascicolo", output = "urn:updateACLFascicoloResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:updateACLFascicoloWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "updateACLFascicolo", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.UpdateACLFascicolo")
    @WebMethod(action = "urn:updateACLFascicolo")
    @ResponseWrapper(localName = "updateACLFascicoloResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.UpdateACLFascicoloResponse")
    public java.lang.Boolean updateACLFascicolo(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "fascicoloid", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> fascicoloid,
        @WebParam(name = "acl", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> acl
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:fascicolaById", output = "urn:fascicolaByIdResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:fascicolaByIdWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "fascicolaById", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.FascicolaById")
    @WebMethod(action = "urn:fascicolaById")
    @ResponseWrapper(localName = "fascicolaByIdResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.FascicolaByIdResponse")
    public java.lang.String fascicolaById(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "documentId", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.Long documentId,
        @WebParam(name = "datiFascicolo", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String datiFascicolo
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:logout", output = "urn:logoutResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:logoutWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "logout", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.Logout")
    @WebMethod(action = "urn:logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.LogoutResponse")
    public java.lang.Boolean logout(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:changeACLFascicolo", output = "urn:changeACLFascicoloResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:changeACLFascicoloWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "changeACLFascicolo", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ChangeACLFascicolo")
    @WebMethod(action = "urn:changeACLFascicolo")
    @ResponseWrapper(localName = "changeACLFascicoloResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ChangeACLFascicoloResponse")
    public java.lang.Boolean changeACLFascicolo(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "fascicoloId", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> fascicoloId,
        @WebParam(name = "aclToAdd", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> aclToAdd,
        @WebParam(name = "aclToRemove", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<java.lang.String> aclToRemove
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:loginSSO", output = "urn:loginSSOResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:loginSSOWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "loginSSO", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.LoginSSO")
    @WebMethod(action = "urn:loginSSO")
    @ResponseWrapper(localName = "loginSSOResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.LoginSSOResponse")
    public java.lang.String loginSSO(
        @WebParam(name = "saml", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String saml,
        @WebParam(name = "codiceEnte", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String codiceEnte
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:readConfig", output = "urn:readConfigResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:readConfigWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "readConfig", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ReadConfig")
    @WebMethod(action = "urn:readConfig")
    @ResponseWrapper(localName = "readConfigResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ReadConfigResponse")
    public java.lang.String readConfig(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token
    ) throws WSFascicolazioneFascicolazioneException_Exception;

    @WebResult(name = "return", targetNamespace = "http://fascicolazione.docer.kdm.it")
    @Action(input = "urn:forzaNuovoFascicolo", output = "urn:forzaNuovoFascicoloResponse", fault = {@FaultAction(className = WSFascicolazioneFascicolazioneException_Exception.class, value = "urn:forzaNuovoFascicoloWSFascicolazioneFascicolazioneException")})
    @RequestWrapper(localName = "forzaNuovoFascicolo", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ForzaNuovoFascicolo")
    @WebMethod(action = "urn:forzaNuovoFascicolo")
    @ResponseWrapper(localName = "forzaNuovoFascicoloResponse", targetNamespace = "http://fascicolazione.docer.kdm.it", className = "it.kdm.docer.fascicolazione.ForzaNuovoFascicoloResponse")
    public java.lang.String forzaNuovoFascicolo(
        @WebParam(name = "token", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.lang.String token,
        @WebParam(name = "metadati", targetNamespace = "http://fascicolazione.docer.kdm.it")
        java.util.List<it.kdm.docer.sdk.classes.xsd.KeyValuePair> metadati
    ) throws WSFascicolazioneFascicolazioneException_Exception;
}
