//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.25 at 10:24:55 AM CET 
//


package it.iride.protocollo.xsd.inviamail.messaggioin;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="annoProt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numProt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="docId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="oggettoMail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="testoMail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mittenteMail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="destinatariMail" type="{}destinatariMailType"/>
 *         &lt;element name="destinatariCCMail" type="{}destinatariCCMailType"/>
 *         &lt;element name="utente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ruolo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="invioInteroperabile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annoProt",
    "numProt",
    "docId",
    "oggettoMail",
    "testoMail",
    "mittenteMail",
    "destinatariMail",
    "destinatariCCMail",
    "utente",
    "ruolo",
    "invioInteroperabile"
})
@XmlRootElement(name = "messaggioIn")
public class MessaggioIn {

    protected String annoProt;
    protected String numProt;
    @XmlElement(required = true)
    protected String docId;
    @XmlElement(required = true)
    protected String oggettoMail;
    @XmlElement(required = true)
    protected String testoMail;
    @XmlElement(required = true)
    protected String mittenteMail;
    @XmlElement(required = true)
    protected DestinatariMailType destinatariMail;
    @XmlElement(required = true)
    protected DestinatariCCMailType destinatariCCMail;
    @XmlElement(required = true)
    protected String utente;
    @XmlElement(required = true)
    protected String ruolo;
    protected String invioInteroperabile;

    /**
     * Gets the value of the annoProt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnoProt() {
        return annoProt;
    }

    /**
     * Sets the value of the annoProt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnoProt(String value) {
        this.annoProt = value;
    }

    /**
     * Gets the value of the numProt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumProt() {
        return numProt;
    }

    /**
     * Sets the value of the numProt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumProt(String value) {
        this.numProt = value;
    }

    /**
     * Gets the value of the docId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocId() {
        return docId;
    }

    /**
     * Sets the value of the docId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocId(String value) {
        this.docId = value;
    }

    /**
     * Gets the value of the oggettoMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOggettoMail() {
        return oggettoMail;
    }

    /**
     * Sets the value of the oggettoMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOggettoMail(String value) {
        this.oggettoMail = value;
    }

    /**
     * Gets the value of the testoMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestoMail() {
        return testoMail;
    }

    /**
     * Sets the value of the testoMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestoMail(String value) {
        this.testoMail = value;
    }

    /**
     * Gets the value of the mittenteMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMittenteMail() {
        return mittenteMail;
    }

    /**
     * Sets the value of the mittenteMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMittenteMail(String value) {
        this.mittenteMail = value;
    }

    /**
     * Gets the value of the destinatariMail property.
     * 
     * @return
     *     possible object is
     *     {@link DestinatariMailType }
     *     
     */
    public DestinatariMailType getDestinatariMail() {
        return destinatariMail;
    }

    /**
     * Sets the value of the destinatariMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinatariMailType }
     *     
     */
    public void setDestinatariMail(DestinatariMailType value) {
        this.destinatariMail = value;
    }

    /**
     * Gets the value of the destinatariCCMail property.
     * 
     * @return
     *     possible object is
     *     {@link DestinatariCCMailType }
     *     
     */
    public DestinatariCCMailType getDestinatariCCMail() {
        return destinatariCCMail;
    }

    /**
     * Sets the value of the destinatariCCMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinatariCCMailType }
     *     
     */
    public void setDestinatariCCMail(DestinatariCCMailType value) {
        this.destinatariCCMail = value;
    }

    /**
     * Gets the value of the utente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtente() {
        return utente;
    }

    /**
     * Sets the value of the utente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtente(String value) {
        this.utente = value;
    }

    /**
     * Gets the value of the ruolo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuolo() {
        return ruolo;
    }

    /**
     * Sets the value of the ruolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuolo(String value) {
        this.ruolo = value;
    }

    /**
     * Gets the value of the invioInteroperabile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvioInteroperabile() {
        return invioInteroperabile;
    }

    /**
     * Sets the value of the invioInteroperabile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvioInteroperabile(String value) {
        this.invioInteroperabile = value;
    }

}
