package it.iride.wsprotocollodm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2015-01-16T15:25:58.389+01:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ProtocolloHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProtocolloHttpPost {

    /**
     * Esegue la ricerca di un soggetto per codice amministrazione e codice AOO
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "RicercaAmministrazione")
    public java.lang.String ricercaAmministrazione(
        @WebParam(partName = "CodiceAmmSoggetto", name = "CodiceAmmSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmmSoggetto,
        @WebParam(partName = "CodiceAOOSoggetto", name = "CodiceAOOSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOOSoggetto
    );

    /**
     * Restituisce i dati in formato stringa di un documento protocollato a partire da Anno e Numero di Protocollo nel caso di installazione multiDB
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiDocumentoPlus")
    public java.lang.String leggiDocumentoPlus(
        @WebParam(partName = "FiltroDocumento", name = "FiltroDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String filtroDocumento,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Elimina un allegato a partire dall'identificativo
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "EliminaAllegato")
    public java.lang.String eliminaAllegato(
        @WebParam(partName = "EliminaAllegatoIn", name = "EliminaAllegatoIn", targetNamespace = "http://tempuri.org/")
        java.lang.String eliminaAllegatoIn,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce in formato stringa i dati di un documento eventualmente protocollato a partire da IdDocumento
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiDocumentoString")
    public java.lang.String leggiDocumentoString(
        @WebParam(partName = "IdDocumento", name = "IdDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String idDocumento,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati in formato stringa di un documento eventualmente protocollato a partire dal codice a barre
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiBarcodeString")
    public java.lang.String leggiBarcodeString(
        @WebParam(partName = "Barcode", name = "Barcode", targetNamespace = "http://tempuri.org/")
        java.lang.String barcode,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Collega due documenti a partire dall'identificativo
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "CollegaDocumento")
    public java.lang.String collegaDocumento(
        @WebParam(partName = "CollegaDocumentoIn", name = "CollegaDocumentoIn", targetNamespace = "http://tempuri.org/")
        java.lang.String collegaDocumentoIn,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati di un documento eventualmente protocollato a partire dal codice a barre
     */
    @WebResult(name = "DocumentoOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiBarcode")
    public DocumentoOut leggiBarcode(
        @WebParam(partName = "Barcode", name = "Barcode", targetNamespace = "http://tempuri.org/")
        java.lang.String barcode,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce un documento non protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter a partire da dati in formato stringa e restituisce dati in formato stringa
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "InserisciDocumentoString")
    public java.lang.String inserisciDocumentoString(
        @WebParam(partName = "ProtocolloInStr", name = "ProtocolloInStr", targetNamespace = "http://tempuri.org/")
        java.lang.String protocolloInStr,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Aggiunge uno o piu' allegati ad un documento o protocollo esistente  in formato stringa
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AggiungiAllegatiString")
    public java.lang.String aggiungiAllegatiString(
        @WebParam(partName = "NuoviAllegatiStr", name = "NuoviAllegatiStr", targetNamespace = "http://tempuri.org/")
        java.lang.String nuoviAllegatiStr,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Esegue l'autenticazione su IrideWeb in caso di installazione multiDB
     */
    @WebResult(name = "LoginOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LoginMultiDB")
    public LoginOut loginMultiDB(
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Password", name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati di un documento eventualmente protocollato a partire da IdDocumento
     */
    @WebResult(name = "DocumentoOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiDocumento")
    public DocumentoOut leggiDocumento(
        @WebParam(partName = "IdDocumento", name = "IdDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String idDocumento,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Restituisce i dati di un documento eventualmente protocollato a partire da IdDocumento nel caso di installazione multiDB
     */
    @WebResult(name = "DocumentoOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiDocumentoMultiDB")
    public DocumentoOut leggiDocumentoMultiDB(
        @WebParam(partName = "IdDocumento", name = "IdDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String idDocumento,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Creazione delle copie di un documento o un protocollo (max 100) in formato stringa
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "CreaCopieString")
    public java.lang.String creaCopieString(
        @WebParam(partName = "CreaCopieInStr", name = "CreaCopieInStr", targetNamespace = "http://tempuri.org/")
        java.lang.String creaCopieInStr,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce gli estremi dei documenti (eventualmente solo quelli protocollati) per codice fiscale dell'intestatario
     */
    @WebResult(name = "ProtocolliSoggettoOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "RicercaPerCodiceFiscale")
    public ProtocolliSoggettoOut ricercaPerCodiceFiscale(
        @WebParam(partName = "CodiceFiscale", name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(partName = "SoloProtocollo", name = "SoloProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String soloProtocollo,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Annulla un documento a partire dall'identificativo
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "AnnullaDocumento")
    public java.lang.String annullaDocumento(
        @WebParam(partName = "AnnullaDocumentoIn", name = "AnnullaDocumentoIn", targetNamespace = "http://tempuri.org/")
        java.lang.String annullaDocumentoIn,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Modifica un documento o un protocollo e le anagrafiche (max 500) in formato stringa
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "ModificaDocumentoString")
    public java.lang.String modificaDocumentoString(
        @WebParam(partName = "ProtocolloInStr", name = "ProtocolloInStr", targetNamespace = "http://tempuri.org/")
        java.lang.String protocolloInStr,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Pubblicazione di un documento in formato stringa
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "PubblicazioneDocumento")
    public java.lang.String pubblicazioneDocumento(
        @WebParam(partName = "Pubblicazione", name = "Pubblicazione", targetNamespace = "http://tempuri.org/")
        java.lang.String pubblicazione,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati di un documento protocollato a partire da Anno e Numero di Protocollo
     */
    @WebResult(name = "DocumentoOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiProtocollo")
    public DocumentoOut leggiProtocollo(
        @WebParam(partName = "AnnoProtocollo", name = "AnnoProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String annoProtocollo,
        @WebParam(partName = "NumeroProtocollo", name = "NumeroProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroProtocollo,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Restituisce gli estremi dei documenti (eventualmente solo quelli protocollati) per codice fiscale dell'intestatario in fomrato stringa
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "RicercaPerCodiceFiscaleString")
    public java.lang.String ricercaPerCodiceFiscaleString(
        @WebParam(partName = "CodiceFiscale", name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(partName = "SoloProtocollo", name = "SoloProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String soloProtocollo,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Esegue l'autenticazione su IrideWeb
     */
    @WebResult(name = "LoginOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "Login")
    public LoginOut login(
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Password", name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Restituisce i dati di un documento protocollato a partire da Anno e Numero di Protocollo nel caso di installazione multiDB
     */
    @WebResult(name = "DocumentoOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiProtocolloMultiDB")
    public DocumentoOut leggiProtocolloMultiDB(
        @WebParam(partName = "AnnoProtocollo", name = "AnnoProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String annoProtocollo,
        @WebParam(partName = "NumeroProtocollo", name = "NumeroProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroProtocollo,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce in formato stringa i dati di un soggetto a partire da IdSoggetto o CodiceFiscale
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiAnagrafica")
    public java.lang.String leggiAnagrafica(
        @WebParam(partName = "IdSoggetto", name = "IdSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String idSoggetto,
        @WebParam(partName = "CodiceFiscale", name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce un documento protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter in caso a partire da dati in formato stringa e restituisce dati in formato stringa
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "InserisciProtocolloString")
    public java.lang.String inserisciProtocolloString(
        @WebParam(partName = "ProtocolloInStr", name = "ProtocolloInStr", targetNamespace = "http://tempuri.org/")
        java.lang.String protocolloInStr,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Esegue la ricerca di un soggetto per codice amministrazione e codice AOO in caso di installazione multiDB
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "RicercaAmministrazioneMultiDB")
    public java.lang.String ricercaAmministrazioneMultiDB(
        @WebParam(partName = "CodiceAmmSoggetto", name = "CodiceAmmSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmmSoggetto,
        @WebParam(partName = "CodiceAOOSoggetto", name = "CodiceAOOSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOOSoggetto,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce in formato stringa i dati relativi alle copie di un documento
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiCopie")
    public java.lang.String leggiCopie(
        @WebParam(partName = "LeggiCopieIn", name = "LeggiCopieIn", targetNamespace = "http://tempuri.org/")
        java.lang.String leggiCopieIn,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce i dati utente associati a un documento, un soggetto o un'attivita' 
     */
    @WebResult(name = "EsitoOperazione", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "InserisciDatiUtente")
    public EsitoOperazione inserisciDatiUtente(
        @WebParam(partName = "Appartenenza", name = "Appartenenza", targetNamespace = "http://tempuri.org/")
        java.lang.String appartenenza,
        @WebParam(partName = "Identificativo", name = "Identificativo", targetNamespace = "http://tempuri.org/")
        java.lang.String identificativo,
        @WebParam(partName = "DatiUtente", name = "DatiUtente", targetNamespace = "http://tempuri.org/")
        java.lang.String datiUtente,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce gli estremi dei documenti (eventualmente solo quelli protocollati) per codice fiscale dell'intestatario in caso di installazione multiDB
     */
    @WebResult(name = "ProtocolliSoggettoOut", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "RicercaPerCodiceFiscaleMultiDB")
    public ProtocolliSoggettoOut ricercaPerCodiceFiscaleMultiDB(
        @WebParam(partName = "CodiceFiscale", name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(partName = "SoloProtocollo", name = "SoloProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String soloProtocollo,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati in formato stringa di un documento protocollato a partire da Anno e Numero di Protocollo nel caso di installazione multiDB
     */
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    @WebMethod(operationName = "LeggiProtocolloString")
    public java.lang.String leggiProtocolloString(
        @WebParam(partName = "AnnoProtocollo", name = "AnnoProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String annoProtocollo,
        @WebParam(partName = "NumeroProtocollo", name = "NumeroProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String numeroProtocollo,
        @WebParam(partName = "Utente", name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(partName = "Ruolo", name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(partName = "CodiceAmministrazione", name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(partName = "CodiceAOO", name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );
}
