package it.iride.wsprotocollodm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2015-01-16T15:25:58.369+01:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ProtocolloSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ProtocolloSoap {

    /**
     * Esegue la ricerca di un soggetto per codice amministrazione e codice AOO
     */
    @WebResult(name = "RicercaAmministrazioneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RicercaAmministrazione", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaAmministrazione")
    @WebMethod(operationName = "RicercaAmministrazione", action = "http://tempuri.org/RicercaAmministrazione")
    @ResponseWrapper(localName = "RicercaAmministrazioneResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaAmministrazioneResponse")
    public java.lang.String ricercaAmministrazione(
        @WebParam(name = "CodiceAmmSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmmSoggetto,
        @WebParam(name = "CodiceAOOSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOOSoggetto
    );

    /**
     * Restituisce i dati in formato stringa di un documento protocollato a partire da Anno e Numero di Protocollo nel caso di installazione multiDB
     */
    @WebResult(name = "LeggiDocumentoPlusResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiDocumentoPlus", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumentoPlus")
    @WebMethod(operationName = "LeggiDocumentoPlus", action = "http://tempuri.org/LeggiDocumentoPlus")
    @ResponseWrapper(localName = "LeggiDocumentoPlusResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumentoPlusResponse")
    public java.lang.String leggiDocumentoPlus(
        @WebParam(name = "FiltroDocumento", targetNamespace = "http://tempuri.org/")
        java.lang.String filtroDocumento,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Elimina un allegato a partire dall'identificativo
     */
    @WebResult(name = "EliminaAllegatoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EliminaAllegato", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.EliminaAllegato")
    @WebMethod(operationName = "EliminaAllegato", action = "http://tempuri.org/EliminaAllegato")
    @ResponseWrapper(localName = "EliminaAllegatoResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.EliminaAllegatoResponse")
    public java.lang.String eliminaAllegato(
        @WebParam(name = "EliminaAllegatoIn", targetNamespace = "http://tempuri.org/")
        java.lang.String eliminaAllegatoIn,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce in formato stringa i dati di un documento eventualmente protocollato a partire da IdDocumento
     */
    @WebResult(name = "LeggiDocumentoStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiDocumentoString", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumentoString")
    @WebMethod(operationName = "LeggiDocumentoString", action = "http://tempuri.org/LeggiDocumentoString")
    @ResponseWrapper(localName = "LeggiDocumentoStringResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumentoStringResponse")
    public java.lang.String leggiDocumentoString(
        @WebParam(name = "IdDocumento", targetNamespace = "http://tempuri.org/")
        int idDocumento,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce un documento non protocollato a partire da un documento presente in Documentum ed eventualmente esegue l'avvio dell'iter
     */
    @WebResult(name = "DocumentumOut", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InserisciDocumentoDaDM", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.InserisciDocumentoDaDM")
    @WebMethod(operationName = "InserisciDocumentoDaDM", action = "http://tempuri.org/InserisciDocumentoDaDM")
    @ResponseWrapper(localName = "InserisciDocumentoDaDMResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.InserisciDocumentoDaDMResponse")
    public it.iride.wsprotocollodm.DocumentumOut inserisciDocumentoDaDM(
        @WebParam(name = "DocumentumIn", targetNamespace = "http://tempuri.org/")
        it.iride.wsprotocollodm.DocumentumIn documentumIn,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati in formato stringa di un documento eventualmente protocollato a partire dal codice a barre
     */
    @WebResult(name = "LeggiBarcodeStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiBarcodeString", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiBarcodeString")
    @WebMethod(operationName = "LeggiBarcodeString", action = "http://tempuri.org/LeggiBarcodeString")
    @ResponseWrapper(localName = "LeggiBarcodeStringResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiBarcodeStringResponse")
    public java.lang.String leggiBarcodeString(
        @WebParam(name = "Barcode", targetNamespace = "http://tempuri.org/")
        java.lang.String barcode,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Collega due documenti a partire dall'identificativo
     */
    @WebResult(name = "CollegaDocumentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CollegaDocumento", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.CollegaDocumento")
    @WebMethod(operationName = "CollegaDocumento", action = "http://tempuri.org/CollegaDocumento")
    @ResponseWrapper(localName = "CollegaDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.CollegaDocumentoResponse")
    public java.lang.String collegaDocumento(
        @WebParam(name = "CollegaDocumentoIn", targetNamespace = "http://tempuri.org/")
        java.lang.String collegaDocumentoIn,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati di un documento eventualmente protocollato a partire dal codice a barre
     */
    @WebResult(name = "LeggiBarcodeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiBarcode", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiBarcode")
    @WebMethod(operationName = "LeggiBarcode", action = "http://tempuri.org/LeggiBarcode")
    @ResponseWrapper(localName = "LeggiBarcodeResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiBarcodeResponse")
    public it.iride.wsprotocollodm.DocumentoOut leggiBarcode(
        @WebParam(name = "Barcode", targetNamespace = "http://tempuri.org/")
        java.lang.String barcode,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce un documento protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter in caso di installazione multiDB
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "InserisciProtocolloEAnagraficheMultiDBResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "InserisciProtocolloMultiDB", action = "http://tempuri.org/InserisciProtocolloEAnagraficheMultiDB")
    public InserisciProtocolloEAnagraficheMultiDBResponse inserisciProtocolloMultiDB(
        @WebParam(partName = "parameters", name = "InserisciProtocolloEAnagraficheMultiDB", targetNamespace = "http://tempuri.org/")
        InserisciProtocolloEAnagraficheMultiDB parameters
    );

    /**
     * Inserisce un documento non protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter a partire da dati in formato stringa e restituisce dati in formato stringa
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "InserisciDocumentoEAnagraficheStringResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "InserisciDocumentoString", action = "http://tempuri.org/InserisciDocumentoEAnagraficheString")
    public InserisciDocumentoEAnagraficheStringResponse inserisciDocumentoString(
        @WebParam(partName = "parameters", name = "InserisciDocumentoEAnagraficheString", targetNamespace = "http://tempuri.org/")
        InserisciDocumentoEAnagraficheString parameters
    );

    /**
     * Aggiunge uno o piu' allegati ad un documento o protocollo esistente  in formato stringa
     */
    @WebResult(name = "AggiungiAllegatiStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AggiungiAllegatiString", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegatiString")
    @WebMethod(operationName = "AggiungiAllegatiString", action = "http://tempuri.org/AggiungiAllegatiString")
    @ResponseWrapper(localName = "AggiungiAllegatiStringResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegatiStringResponse")
    public java.lang.String aggiungiAllegatiString(
        @WebParam(name = "NuoviAllegatiStr", targetNamespace = "http://tempuri.org/")
        java.lang.String nuoviAllegatiStr,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Aggiunge uno o piu' allegati ad un documento o protocollo esistente in caso di installazione multiDB
     */
    @WebResult(name = "AggiungiAllegatiMultiDBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AggiungiAllegatiMultiDB", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegatiMultiDB")
    @WebMethod(operationName = "AggiungiAllegatiMultiDB", action = "http://tempuri.org/AggiungiAllegatiMultiDB")
    @ResponseWrapper(localName = "AggiungiAllegatiMultiDBResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegatiMultiDBResponse")
    public java.lang.String aggiungiAllegatiMultiDB(
        @WebParam(name = "NuoviAllegati", targetNamespace = "http://tempuri.org/")
        it.iride.wsprotocollodm.NuoviAllegati nuoviAllegati,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Esegue l'autenticazione su IrideWeb in caso di installazione multiDB
     */
    @WebResult(name = "LoginMultiDBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LoginMultiDB", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LoginMultiDB")
    @WebMethod(operationName = "LoginMultiDB", action = "http://tempuri.org/LoginMultiDB")
    @ResponseWrapper(localName = "LoginMultiDBResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LoginMultiDBResponse")
    public it.iride.wsprotocollodm.LoginOut loginMultiDB(
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati di un documento eventualmente protocollato a partire da IdDocumento
     */
    @WebResult(name = "LeggiDocumentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiDocumento", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumento")
    @WebMethod(operationName = "LeggiDocumento", action = "http://tempuri.org/LeggiDocumento")
    @ResponseWrapper(localName = "LeggiDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumentoResponse")
    public it.iride.wsprotocollodm.DocumentoOut leggiDocumento(
        @WebParam(name = "IdDocumento", targetNamespace = "http://tempuri.org/")
        int idDocumento,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Restituisce i dati di un documento eventualmente protocollato a partire da IdDocumento nel caso di installazione multiDB
     */
    @WebResult(name = "LeggiDocumentoMultiDBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiDocumentoMultiDB", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumentoMultiDB")
    @WebMethod(operationName = "LeggiDocumentoMultiDB", action = "http://tempuri.org/LeggiDocumentoMultiDB")
    @ResponseWrapper(localName = "LeggiDocumentoMultiDBResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiDocumentoMultiDBResponse")
    public it.iride.wsprotocollodm.DocumentoOut leggiDocumentoMultiDB(
        @WebParam(name = "IdDocumento", targetNamespace = "http://tempuri.org/")
        int idDocumento,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Creazione delle copie di un documento o un protocollo (max 100) in formato stringa
     */
    @WebResult(name = "CreaCopieStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreaCopieString", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.CreaCopieString")
    @WebMethod(operationName = "CreaCopieString", action = "http://tempuri.org/CreaCopieString")
    @ResponseWrapper(localName = "CreaCopieStringResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.CreaCopieStringResponse")
    public java.lang.String creaCopieString(
        @WebParam(name = "CreaCopieInStr", targetNamespace = "http://tempuri.org/")
        java.lang.String creaCopieInStr,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce gli estremi dei documenti (eventualmente solo quelli protocollati) per codice fiscale dell'intestatario
     */
    @WebResult(name = "RicercaPerCodiceFiscaleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RicercaPerCodiceFiscale", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaPerCodiceFiscale")
    @WebMethod(operationName = "RicercaPerCodiceFiscale", action = "http://tempuri.org/RicercaPerCodiceFiscale")
    @ResponseWrapper(localName = "RicercaPerCodiceFiscaleResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaPerCodiceFiscaleResponse")
    public it.iride.wsprotocollodm.ProtocolliSoggettoOut ricercaPerCodiceFiscale(
        @WebParam(name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(name = "SoloProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String soloProtocollo,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Annulla un documento a partire dall'identificativo
     */
    @WebResult(name = "AnnullaDocumentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AnnullaDocumento", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AnnullaDocumento")
    @WebMethod(operationName = "AnnullaDocumento", action = "http://tempuri.org/AnnullaDocumento")
    @ResponseWrapper(localName = "AnnullaDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AnnullaDocumentoResponse")
    public java.lang.String annullaDocumento(
        @WebParam(name = "AnnullaDocumentoIn", targetNamespace = "http://tempuri.org/")
        java.lang.String annullaDocumentoIn,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce un documento non protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter in caso di installazione multiDM
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "InserisciDocumentoEAnagraficheMultiDBResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "InserisciDocumentoMultiDB", action = "http://tempuri.org/InserisciDocumentoEAnagraficheMultiDB")
    public InserisciDocumentoEAnagraficheMultiDBResponse inserisciDocumentoMultiDB(
        @WebParam(partName = "parameters", name = "InserisciDocumentoEAnagraficheMultiDB", targetNamespace = "http://tempuri.org/")
        InserisciDocumentoEAnagraficheMultiDB parameters
    );

    /**
     * Inserisce un documento protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "InserisciProtocolloEAnagraficheResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "InserisciProtocollo", action = "http://tempuri.org/InserisciProtocolloEAnagrafiche")
    public InserisciProtocolloEAnagraficheResponse inserisciProtocollo(
        @WebParam(partName = "parameters", name = "InserisciProtocolloEAnagrafiche", targetNamespace = "http://tempuri.org/")
        InserisciProtocolloEAnagrafiche parameters
    );

    /**
     * Modifica un documento o un protocollo e le anagrafiche (max 500) in formato stringa
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ModificaDocumentoEAnagraficheStringResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "ModificaDocumentoString", action = "http://tempuri.org/ModificaDocumentoEAnagraficheString")
    public ModificaDocumentoEAnagraficheStringResponse modificaDocumentoString(
        @WebParam(partName = "parameters", name = "ModificaDocumentoEAnagraficheString", targetNamespace = "http://tempuri.org/")
        ModificaDocumentoEAnagraficheString parameters
    );

    /**
     * Aggiunge uno o piu' allegati ad un documento o protocollo esistente
     */
    @WebResult(name = "AggiungiAllegatiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AggiungiAllegati", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegati")
    @WebMethod(operationName = "AggiungiAllegati", action = "http://tempuri.org/AggiungiAllegati")
    @ResponseWrapper(localName = "AggiungiAllegatiResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegatiResponse")
    public java.lang.String aggiungiAllegati(
        @WebParam(name = "NuoviAllegati", targetNamespace = "http://tempuri.org/")
        it.iride.wsprotocollodm.NuoviAllegati nuoviAllegati
    );

    /**
     * Pubblicazione di un documento in formato stringa
     */
    @WebResult(name = "PubblicazioneDocumentoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PubblicazioneDocumento", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.PubblicazioneDocumento")
    @WebMethod(operationName = "PubblicazioneDocumento", action = "http://tempuri.org/PubblicazioneDocumento")
    @ResponseWrapper(localName = "PubblicazioneDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.PubblicazioneDocumentoResponse")
    public java.lang.String pubblicazioneDocumento(
        @WebParam(name = "Pubblicazione", targetNamespace = "http://tempuri.org/")
        java.lang.String pubblicazione,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati di un documento protocollato a partire da Anno e Numero di Protocollo
     */
    @WebResult(name = "LeggiProtocolloResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiProtocollo", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiProtocollo")
    @WebMethod(operationName = "LeggiProtocollo", action = "http://tempuri.org/LeggiProtocollo")
    @ResponseWrapper(localName = "LeggiProtocolloResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiProtocolloResponse")
    public it.iride.wsprotocollodm.DocumentoOut leggiProtocollo(
        @WebParam(name = "AnnoProtocollo", targetNamespace = "http://tempuri.org/")
        short annoProtocollo,
        @WebParam(name = "NumeroProtocollo", targetNamespace = "http://tempuri.org/")
        int numeroProtocollo,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Restituisce i dati di un documento protocollato a partire da Anno e Numero di Protocollo nel caso di installazione multiDB
     */
    @WebResult(name = "LeggiProtocolloMultiDBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiProtocolloMultiDB", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiProtocolloMultiDB")
    @WebMethod(operationName = "LeggiProtocolloMultiDB", action = "http://tempuri.org/LeggiProtocolloMultiDB")
    @ResponseWrapper(localName = "LeggiProtocolloMultiDBResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiProtocolloMultiDBResponse")
    public it.iride.wsprotocollodm.DocumentoOut leggiProtocolloMultiDB(
        @WebParam(name = "AnnoProtocollo", targetNamespace = "http://tempuri.org/")
        short annoProtocollo,
        @WebParam(name = "NumeroProtocollo", targetNamespace = "http://tempuri.org/")
        int numeroProtocollo,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce un documento protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter in caso a partire da dati in formato stringa e restituisce dati in formato stringa
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "InserisciProtocolloEAnagraficheStringResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "InserisciProtocolloString", action = "http://tempuri.org/InserisciProtocolloEAnagraficheString")
    public InserisciProtocolloEAnagraficheStringResponse inserisciProtocolloString(
        @WebParam(partName = "parameters", name = "InserisciProtocolloEAnagraficheString", targetNamespace = "http://tempuri.org/")
        InserisciProtocolloEAnagraficheString parameters
    );

    /**
     * Creazione delle copie di un documento o un protocollo (max 100)
     */
    @WebResult(name = "CreaCopieResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreaCopie", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.CreaCopie")
    @WebMethod(operationName = "CreaCopie", action = "http://tempuri.org/CreaCopie")
    @ResponseWrapper(localName = "CreaCopieResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.CreaCopieResponse")
    public it.iride.wsprotocollodm.CreaCopieOut creaCopie(
        @WebParam(name = "CreaCopieIn", targetNamespace = "http://tempuri.org/")
        it.iride.wsprotocollodm.CreaCopieIn creaCopieIn,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Aggiunge uno o piu' allegati ad un documento o protocollo esistente - nuovo messaggio di ritorno
     */
    @WebResult(name = "AggiungiAllegati2Result", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AggiungiAllegati2", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegati2")
    @WebMethod(operationName = "AggiungiAllegati2", action = "http://tempuri.org/AggiungiAllegati2")
    @ResponseWrapper(localName = "AggiungiAllegati2Response", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.AggiungiAllegati2Response")
    public it.iride.wsprotocollodm.AllegatiInseritiOut aggiungiAllegati2(
        @WebParam(name = "NuoviAllegati", targetNamespace = "http://tempuri.org/")
        it.iride.wsprotocollodm.NuoviAllegati nuoviAllegati,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Modifica un documento o un protocollo e le anagrafiche (max 500)
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "ModificaDocumentoEAnagraficheResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "ModificaDocumento", action = "http://tempuri.org/ModificaDocumentoEAnagrafiche")
    public ModificaDocumentoEAnagraficheResponse modificaDocumento(
        @WebParam(partName = "parameters", name = "ModificaDocumentoEAnagrafiche", targetNamespace = "http://tempuri.org/")
        ModificaDocumentoEAnagrafiche parameters
    );

    /**
     * Restituisce gli estremi dei documenti (eventualmente solo quelli protocollati) per codice fiscale dell'intestatario in fomrato stringa
     */
    @WebResult(name = "RicercaPerCodiceFiscaleStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RicercaPerCodiceFiscaleString", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaPerCodiceFiscaleString")
    @WebMethod(operationName = "RicercaPerCodiceFiscaleString", action = "http://tempuri.org/RicercaPerCodiceFiscaleString")
    @ResponseWrapper(localName = "RicercaPerCodiceFiscaleStringResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaPerCodiceFiscaleStringResponse")
    public java.lang.String ricercaPerCodiceFiscaleString(
        @WebParam(name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(name = "SoloProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String soloProtocollo,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Esegue l'autenticazione su IrideWeb
     */
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.Login")
    @WebMethod(operationName = "Login", action = "http://tempuri.org/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LoginResponse")
    public it.iride.wsprotocollodm.LoginOut login(
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo
    );

    /**
     * Restituisce in formato stringa i dati di un soggetto a partire da IdSoggetto o CodiceFiscale
     */
    @WebResult(name = "LeggiAnagraficaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiAnagrafica", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiAnagrafica")
    @WebMethod(operationName = "LeggiAnagrafica", action = "http://tempuri.org/LeggiAnagrafica")
    @ResponseWrapper(localName = "LeggiAnagraficaResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiAnagraficaResponse")
    public java.lang.String leggiAnagrafica(
        @WebParam(name = "IdSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String idSoggetto,
        @WebParam(name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Esegue la ricerca di un soggetto per codice amministrazione e codice AOO in caso di installazione multiDB
     */
    @WebResult(name = "RicercaAmministrazioneMultiDBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RicercaAmministrazioneMultiDB", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaAmministrazioneMultiDB")
    @WebMethod(operationName = "RicercaAmministrazioneMultiDB", action = "http://tempuri.org/RicercaAmministrazioneMultiDB")
    @ResponseWrapper(localName = "RicercaAmministrazioneMultiDBResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaAmministrazioneMultiDBResponse")
    public java.lang.String ricercaAmministrazioneMultiDB(
        @WebParam(name = "CodiceAmmSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmmSoggetto,
        @WebParam(name = "CodiceAOOSoggetto", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOOSoggetto,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce in formato stringa i dati relativi alle copie di un documento
     */
    @WebResult(name = "LeggiCopieResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiCopie", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiCopie")
    @WebMethod(operationName = "LeggiCopie", action = "http://tempuri.org/LeggiCopie")
    @ResponseWrapper(localName = "LeggiCopieResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiCopieResponse")
    public java.lang.String leggiCopie(
        @WebParam(name = "LeggiCopieIn", targetNamespace = "http://tempuri.org/")
        java.lang.String leggiCopieIn,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce i dati utente associati a un documento, un soggetto o un'attivita' 
     */
    @WebResult(name = "InserisciDatiUtenteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InserisciDatiUtente", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.InserisciDatiUtente")
    @WebMethod(operationName = "InserisciDatiUtente", action = "http://tempuri.org/InserisciDatiUtente")
    @ResponseWrapper(localName = "InserisciDatiUtenteResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.InserisciDatiUtenteResponse")
    public it.iride.wsprotocollodm.EsitoOperazione inserisciDatiUtente(
        @WebParam(name = "Appartenenza", targetNamespace = "http://tempuri.org/")
        java.lang.String appartenenza,
        @WebParam(name = "Identificativo", targetNamespace = "http://tempuri.org/")
        int identificativo,
        @WebParam(name = "DatiUtente", targetNamespace = "http://tempuri.org/")
        java.lang.String datiUtente,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Inserisce un documento non protocollato e le anagrafiche (max 100) ed eventualmente esegue l'avvio dell'iter
     */
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "InserisciDocumentoEAnagraficheResponse", targetNamespace = "http://tempuri.org/", partName = "parameters")
    @WebMethod(operationName = "InserisciDocumento", action = "http://tempuri.org/InserisciDocumentoEAnagrafiche")
    public InserisciDocumentoEAnagraficheResponse inserisciDocumento(
        @WebParam(partName = "parameters", name = "InserisciDocumentoEAnagrafiche", targetNamespace = "http://tempuri.org/")
        InserisciDocumentoEAnagrafiche parameters
    );

    /**
     * Restituisce gli estremi dei documenti (eventualmente solo quelli protocollati) per codice fiscale dell'intestatario in caso di installazione multiDB
     */
    @WebResult(name = "RicercaPerCodiceFiscaleMultiDBResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RicercaPerCodiceFiscaleMultiDB", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaPerCodiceFiscaleMultiDB")
    @WebMethod(operationName = "RicercaPerCodiceFiscaleMultiDB", action = "http://tempuri.org/RicercaPerCodiceFiscaleMultiDB")
    @ResponseWrapper(localName = "RicercaPerCodiceFiscaleMultiDBResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.RicercaPerCodiceFiscaleMultiDBResponse")
    public it.iride.wsprotocollodm.ProtocolliSoggettoOut ricercaPerCodiceFiscaleMultiDB(
        @WebParam(name = "CodiceFiscale", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceFiscale,
        @WebParam(name = "SoloProtocollo", targetNamespace = "http://tempuri.org/")
        java.lang.String soloProtocollo,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );

    /**
     * Restituisce i dati in formato stringa di un documento protocollato a partire da Anno e Numero di Protocollo nel caso di installazione multiDB
     */
    @WebResult(name = "LeggiProtocolloStringResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LeggiProtocolloString", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiProtocolloString")
    @WebMethod(operationName = "LeggiProtocolloString", action = "http://tempuri.org/LeggiProtocolloString")
    @ResponseWrapper(localName = "LeggiProtocolloStringResponse", targetNamespace = "http://tempuri.org/", className = "it.iride.wsprotocollodm.LeggiProtocolloStringResponse")
    public java.lang.String leggiProtocolloString(
        @WebParam(name = "AnnoProtocollo", targetNamespace = "http://tempuri.org/")
        short annoProtocollo,
        @WebParam(name = "NumeroProtocollo", targetNamespace = "http://tempuri.org/")
        int numeroProtocollo,
        @WebParam(name = "Utente", targetNamespace = "http://tempuri.org/")
        java.lang.String utente,
        @WebParam(name = "Ruolo", targetNamespace = "http://tempuri.org/")
        java.lang.String ruolo,
        @WebParam(name = "CodiceAmministrazione", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAmministrazione,
        @WebParam(name = "CodiceAOO", targetNamespace = "http://tempuri.org/")
        java.lang.String codiceAOO
    );
}
