
package it.archiflow96.email;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-08-03T11:26:09.140+02:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "XmlSelectNodeFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class IEMailServiceContractRetrieveEmailXmlSelectNodeFaultFaultFaultMessage extends Exception {
    
    private it.archiflow96.email.XmlSelectNodeFault xmlSelectNodeFault;

    public IEMailServiceContractRetrieveEmailXmlSelectNodeFaultFaultFaultMessage() {
        super();
    }
    
    public IEMailServiceContractRetrieveEmailXmlSelectNodeFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEMailServiceContractRetrieveEmailXmlSelectNodeFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEMailServiceContractRetrieveEmailXmlSelectNodeFaultFaultFaultMessage(String message, it.archiflow96.email.XmlSelectNodeFault xmlSelectNodeFault) {
        super(message);
        this.xmlSelectNodeFault = xmlSelectNodeFault;
    }

    public IEMailServiceContractRetrieveEmailXmlSelectNodeFaultFaultFaultMessage(String message, it.archiflow96.email.XmlSelectNodeFault xmlSelectNodeFault, Throwable cause) {
        super(message, cause);
        this.xmlSelectNodeFault = xmlSelectNodeFault;
    }

    public it.archiflow96.email.XmlSelectNodeFault getFaultInfo() {
        return this.xmlSelectNodeFault;
    }
}
