
package it.archiflow96.email;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-08-03T11:26:08.980+02:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "MailFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class IEMailServiceContractSendExtendedMailMailFaultFaultFaultMessage extends Exception {
    
    private it.archiflow96.email.MailFault mailFault;

    public IEMailServiceContractSendExtendedMailMailFaultFaultFaultMessage() {
        super();
    }
    
    public IEMailServiceContractSendExtendedMailMailFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IEMailServiceContractSendExtendedMailMailFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IEMailServiceContractSendExtendedMailMailFaultFaultFaultMessage(String message, it.archiflow96.email.MailFault mailFault) {
        super(message);
        this.mailFault = mailFault;
    }

    public IEMailServiceContractSendExtendedMailMailFaultFaultFaultMessage(String message, it.archiflow96.email.MailFault mailFault, Throwable cause) {
        super(message, cause);
        this.mailFault = mailFault;
    }

    public it.archiflow96.email.MailFault getFaultInfo() {
        return this.mailFault;
    }
}
