
package it.easydoc.MailManagerService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2018-11-06T15:36:25.539+01:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "EasyDocWSException", targetNamespace = "http://www.consorziocsa.it/easydoc/ws")
public class EasyDocWSException extends Exception {
    
    private it.easydoc.MailManagerService.ServiceFaultBean easyDocWSException;

    public EasyDocWSException() {
        super();
    }
    
    public EasyDocWSException(String message) {
        super(message);
    }
    
    public EasyDocWSException(String message, Throwable cause) {
        super(message, cause);
    }

    public EasyDocWSException(String message, it.easydoc.MailManagerService.ServiceFaultBean easyDocWSException) {
        super(message);
        this.easyDocWSException = easyDocWSException;
    }

    public EasyDocWSException(String message, it.easydoc.MailManagerService.ServiceFaultBean easyDocWSException, Throwable cause) {
        super(message, cause);
        this.easyDocWSException = easyDocWSException;
    }

    public it.easydoc.MailManagerService.ServiceFaultBean getFaultInfo() {
        return this.easyDocWSException;
    }
}
