
package it.archiflow93;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2019-02-01T10:12:04.803+01:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "WorkItemNotFoundFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class ICardServiceContractSAPRegisterInvoiceErrorWorkItemNotFoundFaultFaultFaultMessage extends Exception {
    
    private it.archiflow93.WorkItemNotFoundFault workItemNotFoundFault;

    public ICardServiceContractSAPRegisterInvoiceErrorWorkItemNotFoundFaultFaultFaultMessage() {
        super();
    }
    
    public ICardServiceContractSAPRegisterInvoiceErrorWorkItemNotFoundFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICardServiceContractSAPRegisterInvoiceErrorWorkItemNotFoundFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICardServiceContractSAPRegisterInvoiceErrorWorkItemNotFoundFaultFaultFaultMessage(String message, it.archiflow93.WorkItemNotFoundFault workItemNotFoundFault) {
        super(message);
        this.workItemNotFoundFault = workItemNotFoundFault;
    }

    public ICardServiceContractSAPRegisterInvoiceErrorWorkItemNotFoundFaultFaultFaultMessage(String message, it.archiflow93.WorkItemNotFoundFault workItemNotFoundFault, Throwable cause) {
        super(message, cause);
        this.workItemNotFoundFault = workItemNotFoundFault;
    }

    public it.archiflow93.WorkItemNotFoundFault getFaultInfo() {
        return this.workItemNotFoundFault;
    }
}
