
package it.archiflow93;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2019-02-01T10:11:59.604+01:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "LoginFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class ILoginServiceContractLoginWithCredentialAndDeviceTokenLoginFaultFaultFaultMessage extends Exception {
    
    private it.archiflow93.LoginFault loginFault;

    public ILoginServiceContractLoginWithCredentialAndDeviceTokenLoginFaultFaultFaultMessage() {
        super();
    }
    
    public ILoginServiceContractLoginWithCredentialAndDeviceTokenLoginFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ILoginServiceContractLoginWithCredentialAndDeviceTokenLoginFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ILoginServiceContractLoginWithCredentialAndDeviceTokenLoginFaultFaultFaultMessage(String message, it.archiflow93.LoginFault loginFault) {
        super(message);
        this.loginFault = loginFault;
    }

    public ILoginServiceContractLoginWithCredentialAndDeviceTokenLoginFaultFaultFaultMessage(String message, it.archiflow93.LoginFault loginFault, Throwable cause) {
        super(message, cause);
        this.loginFault = loginFault;
    }

    public it.archiflow93.LoginFault getFaultInfo() {
        return this.loginFault;
    }
}
