
package it.archiflow93;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2019-02-01T10:12:08.685+01:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "NoRightsFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class IPostingServiceContractCreateMailServiceSendingNoRightsFaultFaultFaultMessage extends Exception {
    
    private it.archiflow93.NoRightsFault noRightsFault;

    public IPostingServiceContractCreateMailServiceSendingNoRightsFaultFaultFaultMessage() {
        super();
    }
    
    public IPostingServiceContractCreateMailServiceSendingNoRightsFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public IPostingServiceContractCreateMailServiceSendingNoRightsFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IPostingServiceContractCreateMailServiceSendingNoRightsFaultFaultFaultMessage(String message, it.archiflow93.NoRightsFault noRightsFault) {
        super(message);
        this.noRightsFault = noRightsFault;
    }

    public IPostingServiceContractCreateMailServiceSendingNoRightsFaultFaultFaultMessage(String message, it.archiflow93.NoRightsFault noRightsFault, Throwable cause) {
        super(message, cause);
        this.noRightsFault = noRightsFault;
    }

    public it.archiflow93.NoRightsFault getFaultInfo() {
        return this.noRightsFault;
    }
}
