
package it.archiflow96;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2020-08-03T11:26:03.684+02:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "LoginTicketSapFault", targetNamespace = "http://schemas.datacontract.org/2004/07/SIAV.Archiflow.Faults")
public class ICardServiceContractSAPRegisterInvoiceLoginTicketSapFaultFaultFaultMessage extends Exception {
    
    private it.archiflow96.LoginTicketSapFault loginTicketSapFault;

    public ICardServiceContractSAPRegisterInvoiceLoginTicketSapFaultFaultFaultMessage() {
        super();
    }
    
    public ICardServiceContractSAPRegisterInvoiceLoginTicketSapFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ICardServiceContractSAPRegisterInvoiceLoginTicketSapFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ICardServiceContractSAPRegisterInvoiceLoginTicketSapFaultFaultFaultMessage(String message, it.archiflow96.LoginTicketSapFault loginTicketSapFault) {
        super(message);
        this.loginTicketSapFault = loginTicketSapFault;
    }

    public ICardServiceContractSAPRegisterInvoiceLoginTicketSapFaultFaultFaultMessage(String message, it.archiflow96.LoginTicketSapFault loginTicketSapFault, Throwable cause) {
        super(message, cause);
        this.loginTicketSapFault = loginTicketSapFault;
    }

    public it.archiflow96.LoginTicketSapFault getFaultInfo() {
        return this.loginTicketSapFault;
    }
}
